name: Auto Add Reviewers

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Add default reviewers
        uses: peter-evans/add-reviewers@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
            SeungHun-OH
            

